# The URL the site will be built for
base_url = "https://hera.wtf"

theme = "lightspeed"

title = "hera.wtf"
description = "Hera's little corner on the internet."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feed = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "gruvbox-light"

[extra]
# Put all your custom variables here
# I need a redeploy, site broke.

seo = true
author = "Hera Chamorro"
ogimage = "lightning.png"

zola = true
netlify = false
maintained_with_love = true

footer_links = [
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/atom.xml", name = "RSS"},
    {url = "https://github.com/herabit", name = "Github"},
    {url = "https://tech.lgbt/@herabit", name = "Mastodon"}
]
